
# Pandas Final Assignment (Class 2 + Class 3)

### Topics Covered
- head()
- tail()
- info()
- shape
- dtypes
- loc
- iloc
- rename()
- set_index()
- reset_index()
- isnull()
- fillna()
- astype()
- replace()
- drop()
- duplicated()
- drop_duplicates()

### Instructions
- Use Pandas in every question.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display First Rows

## Problem Statement
Create the following DataFrame:

| Name | Age |
|------|-----|
| Aman | 21 |
| Rahul | 22 |
| Neha | 20 |
| Priya | 23 |
| Ravi | 24 |

Display the first 3 rows using `head()`.

## Sample Output
```python
First 3 rows of DataFrame
```

In [2]:
import pandas as pd

a = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha', 'Priya', 'Ravi'],
    'Age' : [21, 22, 20, 23, 24]

})
a

print(a.head(3))

    Name  Age
0   Aman   21
1  Rahul   22
2   Neha   20


# Q2. Display Last Rows

## Problem Statement
Create a DataFrame containing 6 student records.

Display the last 2 rows using `tail()`.

## Sample Output
```python
Last 2 rows of DataFrame
```

In [3]:
a
print(a.tail(2))

    Name  Age
3  Priya   23
4   Ravi   24


# Q3. Check DataFrame Information

## Problem Statement
Create a DataFrame containing:

```python
Name = ["Aman","Rahul","Neha"]
Marks = [80,75,90]
```

Display DataFrame information using `info()`.

## Sample Output
```python
<class 'pandas.core.frame.DataFrame'>
...
```

In [4]:
b = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha'],
    'Marks' : [80, 75, 90]
})
b
print(b.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
None


# Q4. Shape and Data Types

## Problem Statement
Create a DataFrame with:

```python
Name
Age
City
```

Print:
- Shape
- Data Types

## Sample Output
```python
(3,3)
object
int64
```

In [5]:
df = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha'],
    'Age' : [21, 22, 20],
    'City': ['Bhopal', 'Maihar', 'Satna']
})
df

print(df.shape)
print(df.dtypes)

(3, 3)
Name    object
Age      int64
City    object
dtype: object


# Q5. Select Data using loc

## Problem Statement
Create a DataFrame with Name, Age and City.

Using `loc`, display the Name and City of the first row.

## Sample Output
```python
Name    Aman
City    Bhopal
```

In [6]:
df = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha'],
    'Age' : [21, 22, 20],
    'City': ['Bhopal', 'Maihar', 'Satna']
})
df

print(df.iloc[0:1, 0::2])

   Name    City
0  Aman  Bhopal


# Q6. Select Data using iloc

## Problem Statement
Create a DataFrame with at least 4 rows.

Using `iloc`, print:
- Second row
- First two columns

## Sample Output
```python
Selected row values
```

In [7]:
a = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha', 'Priya', 'Ravi'],
    'Age' : [21, 22, 20, 23, 24],
    'Marks': [50, 60, 70, 80, 90],
    'City': ['Bhopal', 'Maihar', 'Satna', 'Rewa', 'Amarpatan']

})
a
print(a.iloc[2:3, 0:2])

   Name  Age
2  Neha   20


# Q7. Rename a Column

## Problem Statement
Create a DataFrame:

```python
Name
Marks
```

Rename column `Marks` to `Score`.

## Sample Output
```python
Name  Score
```

In [8]:
a = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha', 'Priya', 'Ravi'],
    'Marks': [50, 60, 70, 80, 90]

})
a
a.rename(columns={'Marks': 'Score'}, inplace=True)
a

    Name  Score
0   Aman     50
1  Rahul     60
2   Neha     70
3  Priya     80
4   Ravi     90


# Q8. Handle Missing Values

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman", None, "Neha"]
Marks = [80, 75, None]
```

Fill missing values using `fillna()`.

## Sample Output
```python
Missing values replaced
```

In [12]:
a = pd.DataFrame({
    'Name' : ['Aman', None, 'Neha'],
    'Marks': [80, 75, None]

})
a

# a.fillna({'Name':'Riya', 'Marks':90}, inplace = True)
a['Name'].fillna('Riya', inplace = True)
a['Marks'].fillna(25, inplace=True)
a

/var/folders/q5/4x36bfjn5kq3c492jznvbmtw0000gn/T/ipykernel_51780/2323018810.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Name'].fillna('Riya', inplace = True)
/var/folders/q5/4x36bfjn5kq3c492jznvbmtw0000gn/T/ipykernel_51780/2323018810.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Marks'].fillna(25, inplace=True)

   Name  Marks
0  Aman   80.0
1  Riya   75.0
2  Neha   25.0


# Q9. Replace Values

## Problem Statement
Create a DataFrame:

```python
City = ["BPL", "IND", "BPL"]
```

Replace:
- BPL → Bhopal
- IND → Indore

## Sample Output
```python
Bhopal
Indore
Bhopal
```

In [10]:
df = pd.DataFrame({
    'City': ["BPL", "IND", "BPL"]
})
df
df.replace({"BPL":"Bhopal", "IND":"Indore"}, inplace = True)
df

     City
0  Bhopal
1  Indore
2  Bhopal


# Q10. Remove Duplicate Records

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman","Rahul","Aman","Neha"]
```

Check duplicate rows using `duplicated()` and remove them using `drop_duplicates()`.

## Sample Output
```python
Aman
Rahul
Neha
```

In [11]:
df = pd.DataFrame({
    'Name': ["Aman", "Rahul", "Aman", "Neha"]
})
df
df.duplicated()
# df.drop_duplicates()                    #remove in output then if we print the dataframe it will not show any change in original data
df.drop_duplicates(inplace=True)        # so, we use inplace = True to remove duplicates permanently from original data while printing
df

    Name
0   Aman
1  Rahul
3   Neha