# Pandas Assignment - Data Cleaning

Easy to Moderate Level

## Q1. Find Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Riya",None],
    "Age":[21,np.nan,25]
})

Output:
    Name    Age
0  False  False
1  False   True
2   True  False

In [25]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Aman", "Riya", None],
    "Age": [21, np.nan, 25]
})
df

print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False

## Q2. Count Total Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman",None,"Raj"],
    "Age":[20,None,25]
})

Output:
Name    1
Age     1

In [13]:
df = pd.DataFrame({
    "Name": ["Aman", None, "Raj"],
    "Age": [20, None, 25]
})
df

df.isna().sum()

Name    1
Age     1
dtype: int64

## Q3. Fill Missing Age with 0

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "Age":[20,None]
})

Output:
   Name   Age
0  Aman  20.0
1   Raj   0.0

In [14]:
df = pd.DataFrame({
    "Name": ["Aman", "Raj"],
    "Age": [20, None]
})
df
df['Age'].fillna(0, inplace = True)
print(df)

   Name   Age
0  Aman  20.0
1   Raj   0.0

/var/folders/q5/4x36bfjn5kq3c492jznvbmtw0000gn/T/ipykernel_51816/3353441205.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(0, inplace = True)

## Q4. Fill Missing City with 'Unknown'

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal",None]
})

Output:
   Name     City
0  Aman   Bhopal
1   Raj  Unknown

In [15]:
df = pd.DataFrame({
    "Name": ["Aman", "Raj"],
    "City": ["Bhopal", None]
})
df
df['City'].fillna('Unknown', inplace = True)
df

/var/folders/q5/4x36bfjn5kq3c492jznvbmtw0000gn/T/ipykernel_51816/2713109200.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna('Unknown', inplace = True)

   Name     City
0  Aman   Bhopal
1   Raj  Unknown

## Q5. Remove Rows Having Null Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj",None],
    "Age":[20,25,30]
})

Output:
   Name  Age
0  Aman   20
1   Raj   25

In [28]:
df = pd.DataFrame({
    "Name": ["Aman", "Raj", None],
    "Age": [21, 25, 30]
})
df

df.drop(index = 2, inplace = True)
df

   Name  Age
0  Aman   21
1   Raj   25

## Q6. Convert Age Column into Float

Input:
df = pd.DataFrame({"Age":[20,25,30]})

Output:
20.0, 25.0, 30.0

In [29]:
df = pd.DataFrame({
    "Age": [21, 25, 30]
})
df
df.Age.astype(float)

0    21.0
1    25.0
2    30.0
Name: Age, dtype: float64

## Q7. Replace Delhi with New Delhi

Input:
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi"]
})

Output:
New Delhi, Mumbai, New Delhi

In [32]:
df = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Delhi"]
})
df

df.replace('Delhi', 'New Delhi', inplace = True)
df

        City
0  New Delhi
1     Mumbai
2  New Delhi

## Q8. Replace Score 88 with 100

Input:
df = pd.DataFrame({
    "Score":[88,90,88,75]
})

Output:
100,90,100,75

In [ ]:
df = pd.DataFrame({
    "Score": [88, 90, 88, 75]
})
df

df.Score.replace(88, 100, inplace = True)
# df['Score'].replace(88, 100, inplace = True)      # or
df

/var/folders/q5/4x36bfjn5kq3c492jznvbmtw0000gn/T/ipykernel_51816/448505491.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score'].replace(88, 100, inplace = True)

   Score
0    100
1     90
2    100
3     75

## Q9. Drop City Column

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal","Indore"]
})

Output:
   Name
0  Aman
1   Raj

In [39]:
df = pd.DataFrame({
    "Name": ["Aman", "Raj"],
    "City": ["Bhopal", "Indore"]
})
df

df.drop('City', axis = 1, inplace=True)
df

   Name
0  Aman
1   Raj

## Q10. Drop Row at Index 1

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Riya"]
})

Output:
   Name
0  Aman
2  Riya

In [42]:
df = pd.DataFrame({
    "Name": ["Aman", "Raj", "Riya"],
})
df
df.drop(index = 1, axis = 0, inplace = True)
df

   Name
0  Aman
2  Riya

## Q11. Check Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
False, False, True

In [43]:
df = pd.DataFrame({
    "Name": ["Aman", "Raj", "Aman"],
})
df
df.duplicated()

0    False
1    False
2     True
dtype: bool

## Q12. Remove Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
   Name
0  Aman
1   Raj

In [45]:
df = pd.DataFrame({
    "Name": ["Aman", "Raj", "Aman"],
})
df
df.drop_duplicates(inplace = True)
df

   Name
0  Aman
1   Raj

## Q13. Mini Data Cleaning Task

Input:
data = {
    "Name":["Aman","Raj","Aman",None],
    "Age":[20,None,20,25],
    "City":["Bhopal","Delhi","Bhopal","Indore"]
}

Task:
1. Fill missing Age with mean.
2. Remove duplicate rows.
3. Display final DataFrame.

In [50]:
data = pd.DataFrame({
    "Name": ["Aman", "Raj", "Aman", None],
    "Age": [20, None, 20, 25],
    "City": ["Bhopal", "Delhi", "Bhopal", "Indore"]
})
data

data.Age.fillna(data.Age.mean(), inplace = True)
data.drop_duplicates(inplace = True)
print(data)

   Name        Age    City
0  Aman  20.000000  Bhopal
1   Raj  21.666667   Delhi
3  None  25.000000  Indore

/var/folders/q5/4x36bfjn5kq3c492jznvbmtw0000gn/T/ipykernel_51816/1134242424.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Age.fillna(data.Age.mean(), inplace = True)